from utils.llm import ask_llm_json


def run_intervention_agent(farm, context, weather, crop_reasoning):
    fallback = [
        {"name": "Targeted irrigation check and adjustment", "what_to_do": "Verify soil/root-zone moisture and, if the field is genuinely dry, adjust irrigation to the crop's current need rather than irrigating uniformly without verification.", "why_it_may_help": "Addresses the reported water-risk hypothesis while using verification before spending heavily.", "resources": "Water access, basic field inspection, available labor.", "timing": "As soon as practical after verification.", "potential_benefit": "May reduce water-stress risk if insufficient water is confirmed.", "risks": "Unnecessary irrigation can waste water or worsen waterlogging.", "uncertainty": "Actual crop water need and soil moisture are unknown."},
        {"name": "Field inspection plus localized corrective action", "what_to_do": "Inspect representative plants and soil, identify whether symptoms are uniform or localized, then apply only the locally justified corrective action.", "why_it_may_help": "Separates water, pest, disease and nutrient hypotheses before committing resources.", "resources": "Labor and basic field inspection; local extension support if available.", "timing": "Within 24–48 hours where practical.", "potential_benefit": "May reduce the chance of treating the wrong cause.", "risks": "Requires time and may delay intervention.", "uncertainty": "Cause is not confirmed without field evidence."},
        {"name": "Monitor and collect more information", "what_to_do": "Record symptom distribution, inspect soil moisture, check irrigation history and monitor the field before purchasing inputs.", "why_it_may_help": "Creates evidence before spending money when the cause is uncertain.", "resources": "Farmer/labor time and simple observations.", "timing": "Monitor over the next 24–72 hours, depending on crop condition.", "potential_benefit": "Can reduce unnecessary expenditure and improve later decisions.", "risks": "Delay could be costly if severe stress is already developing.", "uncertainty": "Outcome depends on symptom progression and field observations."},
    ]
    prompt = f"""You are the Intervention Agent. Return a JSON array of exactly 3 alternatives for this Pakistani farm. Option 3 should be verification-first or monitor-and-learn when uncertainty is material. Each object must have name, what_to_do, why_it_may_help, resources, timing, potential_benefit, risks, uncertainty. Do not rank the options and do not prescribe chemicals. Farm={farm}; Reasoning={crop_reasoning}; Weather={weather}"""
    out = ask_llm_json(prompt, fallback)
    if isinstance(out, dict) and "options" in out: out = out["options"]
    return out if isinstance(out, list) and len(out) == 3 else fallback
