def build_farm_context(
    province,
    district,
    crop,
    farm_size,
    budget,
    problem,
    main_symptom,
    duration,
    affected_area,
    severity,
    soil_type,
    water_source,
    water_availability,
    recent_irrigation,
    recent_fertilizer,
    recent_pesticide,
):
    return {
        "province": province,
        "district": district,
        "crop": crop,
        "farm_size_acres": farm_size,
        "budget_pkr": budget,
        "problem": problem,
        "main_symptom": main_symptom,
        "duration": duration,
        "affected_area": affected_area,
        "severity": severity,
        "soil_type": soil_type,
        "water_source": water_source,
        "water_availability": water_availability,
        "recent_irrigation": recent_irrigation,
        "recent_fertilizer": recent_fertilizer,
        "recent_pesticide": recent_pesticide,
    }
