"""
Evidence Agent for AGRODECISION PK.

The Evidence Agent receives real research records retrieved by
utils.evidence_search.py and determines which records are relevant
to the agricultural hypotheses.

Important principles:
- It does NOT search the internet itself.
- It does NOT invent citations.
- It can only use evidence records supplied to it.
- It does not treat a paper as proof that a condition exists on a farm.
- It distinguishes research evidence from farmer observations.
- It returns traceable evidence IDs for downstream agents.
"""

from typing import Any, Dict, List

from utils.llm import ask_llm_json
from utils.evidence_search import format_evidence_for_prompt


# ---------------------------------------------------------------------------
# Fallback
# ---------------------------------------------------------------------------


def _build_fallback(
    evidence: List[Dict[str, Any]],
) -> Dict[str, Any]:
    """
    Safe fallback response when the LLM response is invalid.

    The fallback does not make scientific claims. It simply exposes the
    retrieved records as available evidence without claiming that they
    support a particular hypothesis.
    """

    evidence_items = []

    for item in evidence:

        if not isinstance(item, dict):
            continue

        evidence_id = item.get("id")

        if not evidence_id:
            continue

        evidence_items.append(
            {
                "evidence_id": str(evidence_id),
                "relevance": "Unassessed",
                "support_level": "Unassessed",
                "why_relevant": (
                    "This publication was retrieved by the research "
                    "search but its relevance was not assessed because "
                    "the evidence analysis step was unavailable."
                ),
            }
        )

    return {
        "overall_note": (
            "Research records were retrieved automatically, but their "
            "relationship to the reported hypotheses could not be fully "
            "assessed. The records should be reviewed before being used "
            "to support a farm decision."
        ),
        "evidence_assessments": evidence_items,
    }


# ---------------------------------------------------------------------------
# Evidence extraction helpers
# ---------------------------------------------------------------------------


def _extract_hypotheses(
    crop_reasoning: Any,
) -> List[Dict[str, Any]]:
    """
    Extract possible causes/hypotheses from the Crop Agent output.
    """

    if not isinstance(crop_reasoning, dict):
        return []

    causes = crop_reasoning.get("possible_causes")

    if not isinstance(causes, list):
        return []

    valid_causes = []

    for cause in causes:

        if not isinstance(cause, dict):
            continue

        name = cause.get("name")

        if not isinstance(name, str):
            continue

        why = cause.get("why", "")

        if not isinstance(why, str):
            why = str(why)

        confidence = cause.get(
            "confidence",
            "Unknown",
        )

        valid_causes.append(
            {
                "name": name,
                "confidence": confidence,
                "why": why,
            }
        )

    return valid_causes


def _get_valid_evidence_ids(
    evidence: List[Dict[str, Any]],
) -> set:
    """
    Return the set of evidence IDs that actually exist in the retrieved
    evidence records.
    """

    valid_ids = set()

    for item in evidence:

        if not isinstance(item, dict):
            continue

        evidence_id = item.get("id")

        if evidence_id:
            valid_ids.add(str(evidence_id))

    return valid_ids


# ---------------------------------------------------------------------------
# Main Evidence Agent
# ---------------------------------------------------------------------------


def run_evidence_agent(
    farm: Any,
    context: Any,
    weather: Any,
    crop_reasoning: Any,
    evidence: List[Dict[str, Any]],
) -> Dict[str, Any]:
    """
    Analyze automatically retrieved research evidence against the
    hypotheses generated by the Crop Agent.

    Parameters
    ----------
    farm:
        Farmer-provided farm information.

    context:
        Agricultural context.

    weather:
        Weather information.

    crop_reasoning:
        Output from the Crop & Biological Reasoning Agent.

    evidence:
        Real research records retrieved by utils.evidence_search.

    Returns
    -------
    dict
        Structured evidence assessment with traceable evidence IDs.
    """

    fallback = _build_fallback(evidence)

    # ---------------------------------------------------------
    # Validate incoming evidence
    # ---------------------------------------------------------

    if not isinstance(evidence, list):
        return fallback

    valid_evidence = [
        item
        for item in evidence
        if isinstance(item, dict)
        and item.get("id")
        and item.get("title")
    ]

    if not valid_evidence:
        return fallback

    # ---------------------------------------------------------
    # Extract hypotheses
    # ---------------------------------------------------------

    hypotheses = _extract_hypotheses(
        crop_reasoning
    )

    if not hypotheses:
        return fallback

    # ---------------------------------------------------------
    # Format evidence for the LLM
    # ---------------------------------------------------------

    evidence_text = format_evidence_for_prompt(
        valid_evidence
    )

    # ---------------------------------------------------------
    # Build hypothesis section
    # ---------------------------------------------------------

    hypothesis_lines = []

    for index, hypothesis in enumerate(
        hypotheses,
        start=1,
    ):

        hypothesis_lines.append(
            f"""
Hypothesis {index}
Name: {hypothesis["name"]}
Crop Agent confidence: {hypothesis["confidence"]}
Reasoning: {hypothesis["why"]}
""".strip()
        )

    hypothesis_text = "\n\n".join(
        hypothesis_lines
    )

    # ---------------------------------------------------------
    # Prompt
    # ---------------------------------------------------------

    prompt = f"""
You are the Evidence Agent for AGRODECISION PK.

AGRODECISION PK is a human-in-the-loop agricultural decision-support
system for Pakistani agriculture.

Your task is to examine REAL research records retrieved automatically
from a research database and determine how relevant those records are
to the hypotheses generated by the Crop & Biological Reasoning Agent.

You must NOT search for additional papers.

You must NOT invent papers.

You must NOT invent:
- titles
- authors
- journals
- publication years
- DOIs
- URLs
- statistics
- experimental findings
- treatment effects

You may ONLY use the evidence records provided below.

Return valid JSON only.

The JSON must contain exactly these top-level keys:

- "overall_note"
- "evidence_assessments"

"evidence_assessments" must be a list.

Each assessment must contain exactly:

- "evidence_id"
- "relevance"
- "support_level"
- "why_relevant"

"relevance" must be exactly one of:

- "High"
- "Moderate"
- "Low"
- "Not relevant"

"support_level" must be exactly one of:

- "Supports"
- "Partially supports"
- "Does not support"
- "Insufficient information"

IMPORTANT SCIENTIFIC RULES:

1. A research paper does NOT prove that a condition exists on this
   particular farm.

2. A paper may provide background evidence for a biological relationship
   without confirming the farmer's diagnosis.

3. Do not convert correlation into causation.

4. Do not claim that an intervention will work on this farm merely
   because a paper reports an effect elsewhere.

5. Consider differences in:
   - crop
   - cultivar
   - pathogen
   - environmental conditions
   - geographic location
   - experimental design
   - field versus laboratory conditions

6. If the abstract does not provide enough information to establish
   relevance, use:
   "Insufficient information"

7. If a publication is only weakly related to the hypothesis, use:
   "Low"

8. If the publication provides useful but incomplete support, use:
   "Partially supports"

9. If the publication directly supports the biological relationship
   described in the hypothesis, use:
   "Supports"

10. If the paper clearly does not relate to the hypothesis, use:
    "Does not support"

11. Do not give an overall ranking of the hypotheses.

12. Do not identify a "best" hypothesis.

13. Do not diagnose the farm.

14. Keep the assessment understandable to a farmer or agricultural advisor.

15. Every evidence_id must correspond exactly to an Evidence ID supplied
    in the VERIFIED RESEARCH EVIDENCE section.

16. If a research record is not relevant to any hypothesis, it may be
    omitted from "evidence_assessments".

17. Do not invent evidence IDs.

FARM INFORMATION:
{farm}

AGRICULTURAL CONTEXT:
{context}

WEATHER INFORMATION:
{weather}

CROP & BIOLOGICAL HYPOTHESES:
{hypothesis_text}

VERIFIED RESEARCH EVIDENCE:
{evidence_text}
"""

    # ---------------------------------------------------------
    # Ask LLM
    # ---------------------------------------------------------

    result = ask_llm_json(
        prompt,
        fallback,
    )

    if not isinstance(result, dict):
        return fallback

    # ---------------------------------------------------------
    # Validate top-level structure
    # ---------------------------------------------------------

    if set(result.keys()) != {
        "overall_note",
        "evidence_assessments",
    }:
        return fallback

    if not isinstance(
        result.get("overall_note"),
        str,
    ):
        return fallback

    assessments = result.get(
        "evidence_assessments"
    )

    if not isinstance(
        assessments,
        list,
    ):
        return fallback

    # ---------------------------------------------------------
    # Validate evidence IDs
    # ---------------------------------------------------------

    valid_evidence_ids = _get_valid_evidence_ids(
        valid_evidence
    )

    valid_relevance = {
        "High",
        "Moderate",
        "Low",
        "Not relevant",
    }

    valid_support_levels = {
        "Supports",
        "Partially supports",
        "Does not support",
        "Insufficient information",
    }

    required_keys = {
        "evidence_id",
        "relevance",
        "support_level",
        "why_relevant",
    }

    validated = []

    for assessment in assessments:

        if not isinstance(
            assessment,
            dict,
        ):
            return fallback

        if set(assessment.keys()) != required_keys:
            return fallback

        evidence_id = str(
            assessment.get("evidence_id")
        )

        if evidence_id not in valid_evidence_ids:
            return fallback

        relevance = assessment.get(
            "relevance"
        )

        if relevance not in valid_relevance:
            return fallback

        support_level = assessment.get(
            "support_level"
        )

        if support_level not in valid_support_levels:
            return fallback

        why_relevant = assessment.get(
            "why_relevant"
        )

        if not isinstance(
            why_relevant,
            str,
        ):
            return fallback

        validated.append(
            {
                "evidence_id": evidence_id,
                "relevance": relevance,
                "support_level": support_level,
                "why_relevant": why_relevant.strip(),
            }
        )

    result["evidence_assessments"] = validated

    return result


# ---------------------------------------------------------------------------
# Evidence lookup helpers
# ---------------------------------------------------------------------------


def attach_evidence_assessments(
    evidence: List[Dict[str, Any]],
    evidence_analysis: Dict[str, Any],
) -> List[Dict[str, Any]]:
    """
    Merge the Evidence Agent's assessment back into the original
    publication records.

    This gives the final report one complete evidence object containing:

        publication metadata
        abstract
        DOI
        URL
        relevance
        support level
        explanation

    The original publication metadata is never replaced.
    """

    if not isinstance(
        evidence,
        list,
    ):
        return []

    if not isinstance(
        evidence_analysis,
        dict,
    ):
        return evidence

    assessments = evidence_analysis.get(
        "evidence_assessments",
        [],
    )

    if not isinstance(
        assessments,
        list,
    ):
        return evidence

    assessment_map = {}

    for assessment in assessments:

        if not isinstance(
            assessment,
            dict,
        ):
            continue

        evidence_id = assessment.get(
            "evidence_id"
        )

        if not evidence_id:
            continue

        assessment_map[
            str(evidence_id)
        ] = assessment

    enriched = []

    for item in evidence:

        if not isinstance(
            item,
            dict,
        ):
            continue

        enriched_item = dict(item)

        evidence_id = str(
            item.get("id", "")
        )

        assessment = assessment_map.get(
            evidence_id
        )

        if assessment:

            enriched_item[
                "relevance"
            ] = assessment.get(
                "relevance",
                "Unassessed",
            )

            enriched_item[
                "support_level"
            ] = assessment.get(
                "support_level",
                "Unassessed",
            )

            enriched_item[
                "why_relevant"
            ] = assessment.get(
                "why_relevant",
                "",
            )

        else:

            enriched_item[
                "relevance"
            ] = "Unassessed"

            enriched_item[
                "support_level"
            ] = "Unassessed"

            enriched_item[
                "why_relevant"
            ] = ""

        enriched.append(
            enriched_item
        )

    return enriched
